############################################
# InfluxDB v1.x Load Balancer Configuration
############################################

[[connection]]
    name = "10.0.0.1-read"
    location = "http://10.0.0.1:8086"
    ping-endpoint = "/health"
    timeout = "60s"

[[connection]]
    name = "10.0.0.1-write"
    location = "http://10.0.0.1:8086"
    ping-endpoint = "/health"
    timeout = "5s"

[[connection]]
    name = "10.0.0.2-read"
    location = "http://10.0.0.2:8086"
    ping-endpoint = "/health"
    timeout = "60s"

[[connection]]
    name = "10.0.0.2-write"
    location = "http://10.0.0.2:8086"
    ping-endpoint = "/health"
    timeout = "5s"

[[service]]
    name = "influx-read"
    members = ["10.0.0.1-read", "10.0.0.2-read"]

[[service]]
    name = "influx-write"
    members = ["10.0.0.1-write", "10.0.0.2-write"]

[[router]]
    bind = "0.0.0.0:8086"
    access-log = "router_access.log"

    [[router.path]]
        name = "read-path"
        methods = ["GET"]
        incoming-endpoint = "/query"
        [[router.path.target]]
            name = "read-target"
            service = "influx-read"
            request-action = "forward"
            request-strategy = "ping"

    [[router.path]]
        name = "write-path"
        methods = ["POST"]
        incoming-endpoint = "/write"
        [[router.path.target]]
            name = "write-target"
            service = "influx-write"
            request-action = "forward"
            request-strategy = "success"
